services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/leaseweb:/www
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    build: ./php
    container_name: php-fpm
    volumes:
      - ./src/leaseweb:/www
    links:
      - db
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"